docs/index.md
Fixing a few minor grammatical issues in the text and adding links to concepts that may not be clear to everyone.
=> Fix grammar added links

docs/0.2-DRAFT/context.json, docs/0.2-DRAFT/index.md
- Adds a new type to @context WorkflowSketch (ro-terms:Sketch).
-  Added Pronom URIs for sketch example as per spec (but maybe we SHOULD support mime types)
-  Cleaned up a few inconsistencies with SHOULD and MAY
-  Made including creator as a Context Entity a MUST
TODO: s/creator/author/g
=> Edits on first markdown version of draft

docs/index.md
probably not ready to merge, but can improve on this branch.
=> [WIP} first pass at simplifying index page

docs/index.md, docs/outreach.md
See preview at https://github.com/ResearchObject/ro-crate/blob/publications/docs/outreach.md
=> Add list of publications, talks, citations and events

docs/0.2-DRAFT/index.md
Mostly typos, styling etc. I consolidated some content which was fragment across the spec, e.g. we described the RO Website in two different places
=> Proof reading of spec

README.md, docs/0.3-DRAFT/context.json, docs/0.3-DRAFT/index.md
=> context.json is licensed CC0

docs/1.1-DRAFT/index.md
More detail about @type arrays - which were already covered pretty well - inculding a short note about how to code...
=> Added some notes about type arrays and notes on defensive programming

docs/1.1-DRAFT/index.md
=> How to specify ad-hoc properties

docs/1.1-DRAFT/index.md
=> missing "h" in "https"

docs/1.1-DRAFT/index.md
Minor typo fixes and clarifications.
=> Sefton 1.1 review

docs/0.2/index.md, docs/1.0/index.md, docs/1.1-DRAFT/index.md
Fixes an id reference and some typos.
=> Docs fixes

docs/1.1-DRAFT/appendix/implementation-notes.md
Adressing @jmfernandez in https://github.com/ResearchObject/ro-crate/issues/109#issuecomment-716204520
to also explain how BagIt `fetch.txt` relates to RO-Crate `uri`
=> More about BagIt and fetch.txt

docs/1.1/introduction.md, docs/1.2-DRAFT/introduction.md
Proposed patch to correct draft  - fixes #125
=> Bug intro issue 125

docs/1.2-DRAFT/_metadata.liquid
assuming the licensing period should be extended...
=> updating license years in _metadata.liquid

docs/_config.yml
Title of [index page ](https://www.researchobject.org/ro-crate/) is ` - Research Object Crate (RO-Crate)`
and adding back to top button
=> Fixing title of index page

docs/_config.yml, docs/index.md
It could have been because title was in capital!
=> Second try-out for the index page title

docs/1.2-DRAFT/contextual-entities.md
removing odd --> trailer that showed up in the pdf rendering
as well as double 'of' occurrence
=> Fixing typos

docs/profiles.md
Updates the testing profile docs according to the latest changes in [Workflow Testing RO-Crate](https://github.com/crs4/life_monitor/wiki/Workflow-Testing-RO-Crate) (see https://github.com/ResearchObject/ro-crate-py/pull/55 for the background).
=> Update testing profile docs

docs/1.1/appendix/changelog.md, docs/1.1/appendix/implementation-notes.md, docs/1.1/appendix/index.md, docs/1.1/appendix/jsonld.md, docs/1.1/appendix/relative-uris.md, docs/1.1/contextual-entities.md, docs/1.1/data-entities.md, docs/1.1/introduction.md, docs/1.1/metadata.md, docs/1.1/provenance.md, docs/1.1/root-data-entity.md, docs/1.1/structure.md, docs/1.1/terminology.md, docs/1.1/workflows.md
I renamed the title of RO-Crate 1.1 to RO-Crate 1.1 (latest), but forgot to update the metadata of the siblings
=> RO-Crate 1.1 side nav fix

docs/in-use/index.md, docs/index.md
improved and extended the descriptions of RO-Crate in use, mentioned it is also being used for Data, and linked to from the front page
=> Ro in use expanded

docs/Gemfile.lock, docs/in-use/index.md
the text provided by @lrodrin , thanks!
=> added details about the WfExS use case

docs/1.1/metadata.md, docs/1.2-DRAFT/metadata.md
Corrected typo at Metadata Section
=> Typo at Metadata Section

docs/1.1/data-entities.md, docs/1.2-DRAFT/data-entities.md
=> Fix typos in data entities page

docs/1.1/appendix/jsonld.md, docs/1.2-DRAFT/appendix/jsonld.md
Also clarify that we currently we mean rdfs:Class/rdf:Property and not http://schema.org/Class and http://schema.org/Property – but perhaps those would be better?
=> Correct namespace for rdfs:comment

docs/1.2-DRAFT/contextual-entities.md, docs/1.2-DRAFT/data-entities.md, docs/1.2-DRAFT/root-data-entity.md, docs/1.2-DRAFT/terminology.md
after feedback from Rudolf Wittner
=> Attempts to clarify entity terminology

docs/1.2-DRAFT/introduction.md
Fix typos and JSON formatting, adjust some sentences.
=> Review intro

docs/1.1/contextual-entities.md, docs/1.1/workflows.md, docs/1.2-DRAFT/contextual-entities.md, docs/1.2-DRAFT/crate-focus.md, docs/1.2-DRAFT/data-entities.md, docs/1.2-DRAFT/profiles.md, docs/1.2-DRAFT/workflows.md
This morning, looking for a JSON-LD example to test some online chart drawing tools I realized that some examples had minor problems in their JSON syntax, and the complete ones I fixed could not be used in their state due some extra comma or newline.
So this pull request contains those minor , cosmetic fixes
=> Cosmetic fixes to the examples

docs/1.2-DRAFT/profiles.md
but will be raising an issue with the large number of new metadata terms that don't resolve to human readable explanations that have made it into the @context
=> A few minor updates,

docs/tools/index.md
Probably should write up an in-use story as well
https://www.research-data-services.org/
=> Add Sciebo-RDS to Tools

docs/community.md, docs/tutorials.md
Adds the Carpentries-style tutorial and a little detail about each tutorial in the list.
=> Update tutorials page

docs/_data/tools_list.yml
This PR updates the describo links in the tools section.
=> update describo links

docs/pages/use_cases/COMPSs.md
Small fixes to the COMPSs RO-Crate use case
=> COMPSs use case small fixes

docs/_config.yml, docs/assets/js/search-data.json
Fixes #336. 
This is also fixed upstream https://github.com/ELIXIR-Belgium/elixir-toolkit-theme/issues/265 but upgrading to the patched version is its own issue with its own complications #344.
This PR therefore overrides the relevant file from ETT 2.4.0.
=> Include spec pages in search

docs/_includes/references.liquid, docs/_specification/1.1/workflows.md, docs/_specification/1.2-DRAFT/workflows.md
=> Fix minor errors in spec

docs/pages/use_cases/COMPSs.md
Updated WRROC paper reference to the PLOS journal
=> Updated WRROC paper reference

docs/pages/community/outreach.md
.. and WorkflowHub and FAIR Wf preprints.
=> Added WfExS preprint

docs/pages/community/community.md
=> add @AndreasMeier12 to team

docs/_data/tools_list.yml
I'm not 100% sure what values are expected for `level` and `status`, but here is my best guess.
=> Add RdfCrate to `tools_list`

docs/_specification/1.2-DRAFT/contextual-entities.md, docs/_specification/1.2-DRAFT/data-entities.md, docs/_specification/1.2-DRAFT/metadata.md, docs/_specification/1.2-DRAFT/root-data-entity.md, docs/_specification/1.2-DRAFT/structure.md
Fixes https://github.com/ResearchObject/ro-crate/issues/380 and points 1 & 2 from https://github.com/ResearchObject/ro-crate/issues/381.
Replaces #392 since some of the changes were made/affected by #390.
=> Make clarifications in 1.2 text 

docs/_specification/1.2-DRAFT/data-entities.md
Fixes formatting and some typos.
=> Data entities: fix typos and formatting

docs/_includes/references.liquid, docs/_specification/1.2-DRAFT/contextual-entities.md
Review of the section on contextual entities. See commit messages for details.
=> Review Contextual Entities

docs/_specification/1.2-DRAFT/appendix/relative-uris.md
=> Describe limitations of SPARQL query for finding Root Data Entity

docs/_data/tools_list.yml
Fixes #420 
cc @mburridge96 for your information :)
=> add ro-crate-rs to tools page

docs/pages/community/outreach.md, docs/pages/use_cases/5s-crate.md, docs/pages/use_cases/autosubmit.md
=> Add publications from FDO Summit

docs/pages/community/outreach.md
Including from ACM'REP 25
See also [publications on Workflow Run Crate](https://www.researchobject.org/workflow-run-crate/outreach#publications) but I didn't include all of those here, as they don't all use RO-Crate.
=> Updated publications
