ResearchObject/ro-crate

docs/0.3-DRAFT/index.md
This large pull request expands on the role of Linked Data and JSON-LD, targeting readers who may not be familiar with these:
In particular:
* Unified _Context entity_ and _Contextual Entity_ to just the last, to avoid confusion with _JSON-LD context_.
* Structure of [RO-Crate metadata file](https://github.com/ResearchObject/ro-crate/blob/intro-jsonld/docs/0.3-DRAFT/index.md#ro-crate-metadata-file-ro-crate-metadatajsonld)
* Show the overall RO-Crate JSON-LD structure early on.
* Require the JSON-LD to describe the Root Data Entity, Data entities and Contextual entities
* Added [differences from schema.org](https://github.com/ResearchObject/ro-crate/blob/intro-jsonld/docs/0.3-DRAFT/index.md#differences-from-schemaorg) to highlight that not all JSON-LD  examples at http://schema.org/ fit …
=> Add introduction to Linked Data and JSON-LD

docs/0.3-DRAFT/index.md
I redid yesterday's mess based on the master branch. No major re-ordering in this so it should merge OK. Mostly tidying up, but also removes the MUST have tables as per #60 .
Made some changes in the workflow section to make the examples more consistent.
Added @type File (as an array element) to a lot of Data Entities that did not have it (eg Workflow examples that are actually describing files) - I think this would make it easier for coders but maybe we should discuss this.
Hope this is cleaner than yesterday's @stain!
=> Redoing edits

docs/1.1-DRAFT/index.md
Modifying 1.1-DRAFT spec to allow `@id` of Data Entity to be external/absolute URIs, and adds considerations before adding external URI to `hasPart` of an RO-Crate.
See #72 .
=> Adding @id for external URIs

docs/1.1-DRAFT/context.jsonld, docs/1.1-DRAFT/index.md, scripts/schema-context.py
Avoid using `@base: null` as it means parsing RO-Crate JSON-LD as RDF will skip triples with relative URIs. 
Rather adding `@base: null` can be recommended for the compaction algorithm if making RO-Crates.
=> Avoid @base: null as it breaks parsing as RDF

docs/1.1-DRAFT/index.md
My attempt to update the spec to use ro-crate-metadata.json instead of .jsonld.
Have also updated a few references to the file by its filename to use its specification-name: "RO-Crate Metadata File"
=> Addressed #82 - changing the name of the RO Crate Metadata File

docs/1.1-DRAFT/index.md
Added below _Core Metadata for Data Entities_ to clarify #77 
Note that all `@id` [identifiers must be valid URI references](https://researchobject.github.io/ro-crate/1.0/#describing-entities-in-json-ld), care must be taken to express any relative paths using `/` separator, correct casing, and escape special characters like space (`%20`) and percent (`%25`), for instance a _File Data Entity_ from the Windows path `Results and Diagrams\almost-50%.png` becomes `"@id": "Results%20and%20Diagrams/almost-50%25.png"` in the _RO-Crate JSON-LD_.
In this document the term _URI_ includes international _IRI_s; the _RO-Crate Metadata File_ is always UTF-8 and international characters in identifiers SHOULD be written using native UTF-8 characters (_IRI_s), however traditional URL encoding of Unicode …
=> Make it clear that @id is URIpath with / seperators

docs/1.1-DRAFT/index.md
The property `relatedLink` is not needed in the [RepositoryObject hasFile example](https://www.researchobject.org/ro-crate/1.0/#digital-library-and-repository-content), and the use of inline HTML for <http://schema.org/relatedLink> is not matching upstream spec, which expects `URL`.
=> Remove HTML use of relatedLink property

docs/1.1-DRAFT/appendix/jsonld.md
Review for [APPENDIX: RO-Crate JSON-LD](https://www.researchobject.org/ro-crate/1.1-DRAFT/appendix/jsonld.html#handling-relative-uri-references)
* "JSON tooling", line 27. Is there any link that can be added here?
* "see their individual sections", line 83, is there any link that can be added here?
* is the link for this page correct? "(see also notes on [handling relative URI references](#handling-relative-uri-references) below)", line157, refers to a link that happens to be the same link as the one for the whole page
=> Add review for APPENDIX: RO-Crate JSON-LD

docs/1.1-DRAFT/data-entities.md
* Original text, line 193 "RO-Crates can also gather resources on the web". Proposed text "RO-Crates can also gather resources from the web". But I am not sure what you mean here. Is it gather as in collect? Or is it include pointers to resources on the web?
* "traversal", line 288. Not sure traversal or transversal is intended here, in any case, should it not be before download as an adjective?
=> Review of section ## Web-based Data Entities

docs/1.1-DRAFT/appendix/changelog.md, docs/1.1-DRAFT/metadata.md, docs/1.1-DRAFT/provenance.md
.. the namespaced terms don't use dates in the PCDM ontology. The [context.jsonld](https://github.com/ResearchObject/ro-crate/blob/75001bae93b11035f919695a4a8dae66c0166d62/docs/1.1-DRAFT/context.jsonld#L2624) had correct mapping, only the HTML description of that mapping was wrong.
So <https://pcdm.org/2016/04/18/models#hasFile> should be <http://pcdm.org/models#hasFile> etc.
Added link to the PCDM version <https://pcdm.org/2016/04/18/models> in paragraph above.
Also fixes @jmfernandez comment https://github.com/ResearchObject/ro-crate/issues/109#issuecomment-716203692
that `RepositoryFile` incorrectly mapped to `pcdm:Collection` instead of `pcdm:File`
Improve description of `RepositoryObject`/`RepositoryColletion` rename by also noting `RepositoryFile` was renamed.
This also address …
=> Wrong namespace in PCDM links

docs/1.1-DRAFT/appendix/changelog.md, docs/1.1-DRAFT/appendix/implementation-notes.md, docs/1.1-DRAFT/appendix/jsonld.md, docs/1.1-DRAFT/appendix/relative-uris.md, docs/1.1-DRAFT/contextual-entities.md, docs/1.1-DRAFT/data-entities.md, docs/1.1-DRAFT/metadata.md, docs/1.1-DRAFT/provenance.md, docs/1.1-DRAFT/root-data-entity.md, docs/1.1-DRAFT/structure.md, docs/1.1-DRAFT/terminology.md, docs/1.1-DRAFT/workflows.md, docs/README.md, docs/_includes/references.liquid
Following the 1.1.0 RC1 (see #109) I had another read through of the PDF and made smaller edits as I went along.
Notable changes:
* Citation example expanded https://github.com/ResearchObject/ro-crate/commit/12a675481ec2b9b9ce6eb1941b905ca364d7bab4
* Terminology adds property, type, entity https://github.com/ResearchObject/ro-crate/commit/cc10e284de7e7fd6c401cf6a2f2b037dc94884cc
* `author` can also be applied to CreativeWork https://github.com/ResearchObject/ro-crate/commit/e086b8b141daa93e8c280ea4a72f944c5d46f49c
* Provenance section on Software-used now points to Workflows section (and vice versa) https://github.com/ResearchObject/ro-crate/commit/5d898725f370301cbd113b9652739e366e706bca https://github.com/ResearchObject/ro-crate/commit/40de6c7ba9cddd487c6a4f9579cc009ef4868c5c
* `@id` …
=> Stian review edits for 1.1.0

docs/1.2-DRAFT/context.jsonld, docs/1.2-DRAFT/metadata.md, docs/1.2-DRAFT/profiles.md, docs/1.2-DRAFT/root-data-entity.md, docs/_includes/references.liquid, scripts/schema-context.py
See issue #153. 
This adds a section to explain:
* What is an RO-Crate profile? (borrowed from https://www.researchobject.org/ro-crate/profiles.html)
* How to assign an RO-Crate profile
* How to type a formal RO-Crate profile (e.g. SHACL RDF Shape)
* How to assign profiles to other entities
It does *not* (yet) detail the [suggestions on how to formally specify an RO-Crate profile](https://docs.google.com/document/d/1-H6uhKQn-CFaB3WDwgqgQ6fJtQFNQzDA9VxEQq96kxc/edit#heading=h.xhuk5kjevxx2) as a new or adapted expression language. 
This proposal have multiple sections we may not want to all include:
* [Declaring an RO-Crate profile](https://github.com/ResearchObject/ro-crate/blob/profiles/docs/1.2-DRAFT/profiles.md#declaring-an-ro-crate-profile) – expanding `conformsTo` on Metadata File …
=> RO-Crate Profile section

docs/README.md
port that jekyll runs on, described in the instructions, is 4000 rather than 3000
=> Fixed Jekyll Port

docs/1.1/workflows.md, docs/1.2-DRAFT/workflows.md
The hasPart points to a non-existing knime file in the RO-Crate.
=> Wrong knime file in the Complete Workflow Example

docs/1.1/metadata.md, docs/1.1/workflows.md, docs/1.2-DRAFT/context.jsonld, docs/1.2-DRAFT/metadata.md, docs/1.2-DRAFT/workflows.md, docs/_includes/references.liquid, scripts/schema-context.py
Refer to BioSchemas 1.0-RELEASE versions without `/` in their `@id` URIs. Example:
```json
{ "@id": "workflow/alignment.knime",  
"@type": ["File", "SoftwareSourceCode", "ComputationalWorkflow"],
"conformsTo": 
{"@id": "https://bioschemas.org/profiles/ComputationalWorkflow/1.0-RELEASE"},
"input": [  {"@id": "#36aadbd4-4a2d-4e33-83b4-0cbf6a6a8c5b"} ]
},
{
"@id": "#36aadbd4-4a2d-4e33-83b4-0cbf6a6a8c5b",
"@type": "FormalParameter",
"conformsTo": 
{"@id": "https://bioschemas.org/profiles/FormalParameter/1.0-RELEASE"},
"..": ""
}
```
This fixes issue #185
This also removes the early attempt of `sdConformsTo` structure from #154 and adds a footnote:
> This is a liberal interpretation of `conformsTo` as it is the _structured data_ about the workflow (this JSON-LD object) that conforms to the …
=> Update bioschemas citations

docs/1.2-DRAFT/root-data-entity.md
Make it clearer that other schema.org properties can be used on the RO-Crate Root data entity. 
Adds forward link to the sections on license and contextual entities.
=> Internal references for license and contextual entities

docs/profiles.md
relative link was incorrectly pointing to https://www.researchobject.org/ro-crate/researchobject.org/ro-crate/1.2-DRAFT/profiles
=> fix broken link to the profiles crate spec

docs/1.2-DRAFT/profiles.md
To indicate RO-Crate following a particular [profile](https://www.researchobject.org/ro-crate/1.2-DRAFT/profiles), then move so "conformsTo" applied to "./" as suggested in https://github.com/ResearchObject/ro-crate/issues/153#issuecomment-1240446098 (and agreed in calls [2022-09-08](https://docs.google.com/document/d/1qBCqy7GXTPyydjDIC5h0VGS_4TDSzTnlIRg6dhjyAJ4/edit#heading=h.3a974lmk0gw0) and [2022-01-27](https://docs.google.com/document/d/1qBCqy7GXTPyydjDIC5h0VGS_4TDSzTnlIRg6dhjyAJ4/edit#heading=h.yo3tse270vuq)) rather than on `ro-crate-metadata.json` entity.
This means `conformsTo` on the `ro-crate-metadata.json` is only for RO-Crate spec itself (considering it from a JSON/JSON-LD perspective) while profiles about the content/shapes of a class of crates are appliec using `conformsTo` …
=> conformsTo profile applies to root dataset, not metadata file

docs/1.2-DRAFT/workflows.md
`additionalType` and `encodingFormat` are not required in the [1.0 profile](https://bioschemas.org/profiles/FormalParameter/1.0-RELEASE).
=> Update FormalParameter required properties

docs/1.2-DRAFT/appendix/jsonld.md, docs/1.2-DRAFT/profiles.md, docs/1.2-DRAFT/ro-crate-metadata.json, docs/_includes/references.liquid
http://schema.org/DefinedTerm is better than http://schema.org/Thing for pre-existing URIs that are semantic artefacts or concepts. Somewhat equivalent to [skos:Concept](https://www.w3.org/TR/skos-primer/).  This will then be consistent with https://www.researchobject.org/ro-crate/1.2-DRAFT/profiles that also mentions http://schema.org/DefinedTermSet.
For simplification with the profiles, `rdf:Property` / `rdfs:Class` types now optional, so we can stay in schema.org land for lightweight properties using their equivalent http://schema.org/Property and http://schema.org/Class. The RDFS variants are needed to do `rdfs:subPropertyOf` or `rdfs:subClassOf` but not I think needed for just adding a few terms to JSON-LD.
The part about `@context` and ad-hoc terms will still need to be updated to …
=> Ad-hoc terms use DefinedTerm/Class/Property

docs/1.2-DRAFT/data-entities.md
Also make it clear that other `CreativeWork` properties can be used. The use of [WebSite](http://schema.org/WebSite) for file formats is replaced with [WebPage](http://schema.org/WebPage) as there is typically not a whole website just for one file format (and in particular the https://www.nationalarchives.gov.uk/PRONOM/fmt/19 file formats are part of the `nationalarchives.gov.uk` WebSite).
This also fixes #99 by replacing the CWL example with a Gromacs trajectory which has a special page.
=> Clarify properties for data entities, avoid WebSite type

docs/1.2-DRAFT/appendix/relative-uris.md, docs/1.2-DRAFT/root-data-entity.md
Updates the root data entity section as follows:
* Adds a paragraph to the metadata file descriptor spec to allow absolute URIs (e.g., `https://example.org/crate/ro-crate-metadata.json`) when the root data entity is also an absolute URI.
* Changes the recommended algorithm for finding the root data entity to leverage the constraint that the metadata MUST contain an `ro-crate-metadata.json` (or absolute URI whose last path segment is `ro-crate-metadata.json`) entry. This makes the algorithm simpler and more efficient in the "standard" case of a single entry with an `@id` of `ro-crate-metadata.json` (see https://github.com/ResearchObject/ro-crate-py/pull/119).
Note that, in order to make this PR independent from #189, I've avoided using the term "detached crate". If we merge that PR first, …
=> Update docs on finding the root dataset

docs/1.2-DRAFT/contextual-entities.md, docs/1.2-DRAFT/crate-focus.md, docs/1.2-DRAFT/provenance.md, docs/1.2-DRAFT/root-data-entity.md, docs/1.2-DRAFT/workflows.md
I have drafted a new section which attempts to codify the discussions around mentions and mainEntity (I left out `about` as it is too hard to differentiate from `mentions` - this is complicated enough already)
I think this needs to be a short new section because while it belongs int he discussion of metadata on a root dataset it also needs to come after the sections on Data and Contextual entities.
=> Attempting to address #122 and #124 - mainEntity and mentions

docs/1.2-DRAFT/appendix/jsonld.md, docs/1.2-DRAFT/profiles.md
Links the [Ad-hoc section](https://www.researchobject.org/ro-crate/1.2-DRAFT/appendix/jsonld.html#adding-new-or-ad-hoc-vocabulary-terms) to the new [profile section](https://www.researchobject.org/ro-crate/1.2-DRAFT/profiles) and suggest using that profile as a `@context` to avoid repeating terms.
=> Ad-hoc terms can be moved to a Profile Crate

docs/1.2-DRAFT/data-entities.md
Example: https://by-covid.github.io/baseline-use-case-synthetic-crate/ro-crate-preview.html#vaccines_effectiveness_common_data_model_specification/data/metadata/attributes.csv
```json
{
"@id": "attributes.csv",
"@type": "File",
"encodingFormat": ["text/csv", {"@id": "https://www.nationalarchives.gov.uk/PRONOM/x-fmt/18"}],
"conformsTo": {"@id": "https://docs.ropensci.org/dataspice/#create-spice"}
},
{
"@id": "https://www.nationalarchives.gov.uk/PRONOM/x-fmt/18",
"@type": "WebPage",
"name": "Comma-Separated Values format (CSV)"
},
{
"@id": "https://docs.ropensci.org/dataspice/#create-spice",
"@type": "CreativeWork",
"name": "dataspice CSV profile"
}
```
This also adds note to explain conformsTo used on ro-crate-metadata.json and root dataset for profiles (assumes #229)
=> Indicate encoding format profile using conformsTo

docs/1.2-DRAFT/metadata.md, docs/1.2-DRAFT/ro-crate-metadata.json
Together with #255 this fixes #251.
Note that I didn't define the terms with rdfs as they are already defined such upstream. For PCDM the `termCode` reflects the term used in the JSON-LD context as specified in https://www.researchobject.org/ro-crate/1.2-DRAFT/profiles#extension-terms
I added `inDefinedTermSet` back reference to the vocabulary but didn't list all their members, as the remaining classes/properties are NOT part of the RO-Crate core profile.
=> Add DefinedTerm for Profiles vocabulary, PCDM and cite-as

docs/1.2-DRAFT/metadata.md, docs/1.2-DRAFT/root-data-entity.md, docs/_includes/references.liquid
This fixes #239 as re-opened by @ptsefton to specify `cite-as` as well as `identifier` in the case of a persistent identifier.
I also added the profile definition links as part of #251. I think some of these can be removed as they are not referenced in spec.
The Signposting bit should later be consolidated with the "How to retrieve a crate" currently in `profiles.md` to fix #228 #160.
Catering Peter's question on textual citation I added `description` on the `PropertyValue` -- not sure what you think about that.
=> Specify how cite-as and Signposting should be used

docs/1.2-DRAFT/metadata.md, docs/_includes/references.liquid
Namely that @type is required and name SHOULD be present. 
This fixes #225 
Also clarifies that schema.org types should be used.
New text (hyperlinks not shown here):
For all entities listed in an _RO-Crate Metadata Document_ the following principles apply:
1. The entity MUST have a `@id` (see [Describing entities in JSON-LD]())
2. The entity MUST have a `@type`, which MAY be an array. 
3. The `@type` SHOULD include at least one [Schema.org] type, chosen to most accurately describe the entity (ultimate fallback: [Thing]), except where defined in this specification
4. The entity SHOULD have a human-readable `name`, in particular if its `@id` do not go to a human-readable Web page
5. The properties used on the entity SHOULD be applicable to the `@type` (or superclass) according to their …
=> List required properties for entities

docs/1.2-DRAFT/appendix/relative-uris.md, docs/1.2-DRAFT/data-entities.md
New section _Converting from Detached to Attached Crate_ with a suggested algorithm and warnings it may be elaborate. It notes that if the crate is an Attached Crate on the Web then it is easier due to relative paths.
The "Files that are also on the web" section adds `contentUrl` for the purpose of direct download, while `url` can be used for landing pages only - as proposed in https://github.com/ResearchObject/ro-crate/pull/189#issuecomment-1227697348
This completes #189 as this section was marked as `TODO`.
Tagging @jmfernandez @ptsefton @simleo which had views on retrieval in #189.
=> contentUrl for direct download, add section on Converting to Attached RO-Crate

docs/profiles.md
This PR updates the ARC and ISA profiles such that they now also specify the ISA types further down in the hierarchy like Assays, Studies or Protocols. They are based on the new/adapted bioschemas types LabProcess and LabProtocol. Previously, the profile has only been specified for the top level Investigation object.
=> Updated ARC Profile

docs/1.2-DRAFT/context.jsonld, docs/1.2-DRAFT/metadata.md, docs/1.2-DRAFT/ro-crate-metadata.json, docs/1.2-DRAFT/ro-crate-preview.html, docs/_includes/references.liquid, scripts/schema-context.py
This fixes #286.
Note that only two GeoSPARQL terms are included. The rest can be accessed through prefix "geosparql", we won't use prefix "geo" as it would conflict with https://schema.org/geo which will be used to point to the `Geometry` object.
See https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html for more information.
=> Add geosparql vocabulary terms

docs/1.1/data-entities.md
The documentation talks about how directories on the web that are not distributed as archives should be included. The docu also recommends to include all files inside such a directory as `hasPart`. However, no example is given for this. The only example shows how archives can be linked.
This PR adds an example that links to a web dir that also lists individual files of the dataset.
=> add example for directories on the web to specification

docs/1.2-DRAFT/appendix/jsonld.md, docs/1.2-DRAFT/context.jsonld, docs/1.2-DRAFT/contextual-entities.md
@marc-portier asking you to review as you may have advice about how to add projection info to the asWKT string value
(We can't do anything more complicated using @value constructs as tools don't support this (yet))
=> Trying again, how to do geolocation using asWKT -- addresses #266 

docs/1.2-DRAFT/data-entities.md, docs/_includes/references.liquid
Following a discussion on Slack about how to describe files which are available locally AND on the web (in this case in ROHub) I have strengthened the wording to make it clear that in this case the `@id` should use a relative URI to point to the local file and contentUrl should point to the download.
Including the folks who were part of that conversation as reviewers.
=> Made the language about hybrid attached/detatched crates stronger

docs/pages/resources/profiles.md
Minor bugfixes in ISA profile: now uses correct schema.org terminology for the property `additionalType`.
=> Updated profiles page with bugfixes in ISA profile

docs/_sass/_custom_classes.scss
The font paths aren't right in the deployed site (again because local setup has small differences). This should fix them - as tested on [my fork](https://elichad.github.io/ro-crate/)
=> Use relative path for fonts

docs/_data/sidebars/spec.yml, docs/_specification/1.1/index.md, docs/_specification/1.2-DRAFT/index.md
Fixes #328 in two ways:
- version menu now expands in the sidebar when you go to the landing page for a version (this was broken because the urls set in the sidebar YAML weren't matching the pages exactly)
- lists all the pages on the landing page as well for good measure (like the old site had)
https://github.com/user-attachments/assets/2fb9bf28-916d-43fc-ad80-00b01eae5f40
=> Improve visibility of child spec pages

docs/_data/tools_list.yml
Not sure whether to remove the `ro-crates-deposit` entry or leave it in with an indication that it's inactive.
=> Add ro-crate-zenodo and ro-crate-inveniordm tools to list

docs/_data/footer.yml, docs/_includes/footer.html, docs/_sass/_custom_classes.scss
Instead of overriding the ETT footer, use the default footer and use css / yaml config to avoid showing any links. 
This has the benefit of better maintainability (easier ETT version upgrades) and supporting footer links later if we decide to add some. This also reinstates the ETT logo in the footer, so fixes #316.
=> Revert to ETT footer and customise it with YAML/CSS

docs/_sass/_custom_classes.scss, docs/index.html
Fixes #319 . @smza this was something you mentioned a few weeks ago – do you have any feedback on this?
Adds links to the [about page](https://www.researchobject.org/ro-crate/about_ro_crate) and the [tutorials page](https://www.researchobject.org/ro-crate/tutorials) below the RO-Crate title and tag line on the homepage:
=> Add getting started links to RO-Crate homepage

docs/_data/tools_list.yml
.. and deprecated ro-crate-validator-py
@simleo may want to check on name to be listed as, I think we should link to pypi.
=> added roc-validator

docs/pages/resources/profiles.md
Updated ARC related profiles, since some aspects within them where outdated. Also added a new sub-profile for the CWL part of ARCs (extension of workflow run crate, see https://github.com/nfdi4plants/arc-cwl-ro-crate-profile). For easier maintenance, we decided to remove the explicit part on the RO-Crate website and only refer to the profile's repository.
=> Updated ARC related profiles

docs/_specification/1.2-DRAFT/appendix/changelog.md, docs/_specification/1.2-DRAFT/root-data-entity.md
This algorithm appendum to look for `..../ro-crate-metadata.json` URLs seems unnecessary as such JSON-LDs is not conforming to 1.2, 1.1, 1.0 nor 0.2
=> Remove heuristic for nested ro-crate metadata files

docs/_includes/references.liquid, docs/_sass/_bootstrap_variables.scss, docs/_specification/1.2-DRAFT/contextual-entities.md, docs/_specification/1.2-DRAFT/data-entities.md, docs/_specification/1.2-DRAFT/introduction.md, docs/_specification/1.2-DRAFT/metadata.md, docs/_specification/1.2-DRAFT/root-data-entity.md, docs/_specification/1.2-DRAFT/structure.md, docs/_specification/1.2-DRAFT/terminology.md
Lots of very minor changes from proofreading the first few sections of the spec. For example:
- fixing incorrect spelling/grammar
- consistently using "an RO-Crate" rather than "a RO-Crate"
- consistently italicising and capitalising keywords like _RO-Crate Root_
- adding missing links in references
- reverting the font size for most headings to Bootstrap defaults as some of them are currently too small and not distinct from the text (see for example https://www.researchobject.org/ro-crate/specification/1.2-DRAFT/data-entities.html#referencing-other-ro-crates)
Anything that needs more discussion or careful double-checking I have saved for a separate issue/PR so as not to hide important things in a sea of tiny changes :)
=> Minor grammar, style, and clarity improvements in spec - sections Introduction to Data Entities

docs/pages/community/community.md
Latest additions from #1 .
Making a PR rather than committing straight to `main` as I want to check how best to include a group rather than an individual - @stain @ptsefton what do you think about this?
=> Add new contributors to team

docs/_includes/references.liquid, docs/_specification/1.2-DRAFT/appendix/changelog.md, docs/_specification/1.2-DRAFT/appendix/relative-uris.md, docs/_specification/1.2-DRAFT/contextual-entities.md, docs/_specification/1.2-DRAFT/crate-focus.md, docs/_specification/1.2-DRAFT/data-entities.md, docs/_specification/1.2-DRAFT/profiles.md, docs/_specification/1.2-DRAFT/provenance.md, docs/_specification/1.2-DRAFT/structure.md, docs/_specification/1.2-DRAFT/workflows.md
Lots of very minor changes from proofreading the second half of the spec (not including the appendix). For example:
- fixing incorrect spelling/grammar
- consistently italicising and capitalising keywords like RO-Crate Root
- changing "Root dataset" to "Root Data Entity" for consistency
- adding missing links in references
Anything that needs more discussion or careful double-checking I have saved for a separate issue/PR.
=> Minor grammar, style, and clarity improvements in spec - sections Contextual Entities to Workflows and Scripts

docs/_includes/references.liquid, docs/_specification/1.2-DRAFT/appendix/implementation-notes.md
Hello,
Please consider adding this note into the documentation :)
Cheers,
~Nicolas
=> doc: packaging: add ELN implementation note in appendix

docs/_specification/1.2-DRAFT/profiles.md, docs/_specification/1.2-DRAFT/root-data-entity.md
Fixes #393.
Summary of added requirements (as mentioned in linked issue):
* Metadata descriptor SHOULD have a single value for conformsTo, but it MAY be an array for legacy crates (1.1 and earlier).
* If the crate conforms to one or more profiles, each profile SHOULD be included in conformsTo on the Root Data Entity, and MUST have a corresponding contextual entity
=> Clarify guidance around where and how to declare profile conformance

docs/_specification/1.2-DRAFT/structure.md
This is a review of the RO-Crate Structure section:
* Fix typos
* Move links to first occurrence of related term
* Clarify a sentence on the payload
=> Structure review

docs/_specification/1.2-DRAFT/data-entities.md
In short, `File` and `Dataset` entities are data entities if they use an absolute or relative URI, and not data entities if they use a local identifier starting with `#`.
Fixes(?) #400 
See https://github.com/ResearchObject/ro-crate/issues/400#issuecomment-2779152885 for further explanation
=> Clarify when File/Dataset entities are and are not data entities

docs/pages/community/community.md
Adds links and an embed (shown in screenshot) for the community calendar.
=> Add RO-Crate community calendar to community page

docs/pages/community/community.md
Extra work is needed to make the timezone dynamic based on user locale, so for now, just set it to UTC so it's universally inconvenient.
=> remove London timezone from embedded calendar

docs/pages/use_cases/dataplant.md
While researching something, I noticed that several of the links in the ARC Use case were broken. I did my best to update them to point to relevant resources (e.g. https://arc-rdm.org)
=> doc: Update DataPLANT/Arc Links

docs/pages/resources/vocabularies.md
It's missing a top-level heading
=> Add missing heading to vocabularies page

docs/_data/sidebars/resources.yml, docs/_data/topnav.yml
People often struggle to find the profiles on the website, they are under "Resources" but people don't often look there.
This PR renames "Resources" to "Resources & Profiles" in the navbar & sidebar to help people get to the right section. Screenshot below.
Fixes #330.
=> Mention profiles in topnav to make it easier to find them

docs/_blog/.template.md, docs/_config.yml, docs/_includes/related_use_cases.html, docs/_includes/section-navigation-tiles.html, docs/_layouts/post.html
This will allow blog posts to include related use cases in the front matter, and they will be displayed at the end of the blog post.
For example, adding the following front matter to an example post:
```
related_pages:
use_cases: [workflowhub, digital-twins]
```
Will result in the following rendering:
Inspired by #478
=> Add related use cases to blog posts
